version: '3'
services:
  pg_db:
    container_name: pg_db
    image: postgres
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev
    ports:
      - "5433:5432"
    networks:
      - dev
  spring_boot_example:
    container_name: develcode
    image: develcode/example
    depends_on:
      - pg_db
    ports:
      - "8081:8080"
    networks:
      - dev
networks:
  dev:
    driver: bridge
